### ISSUE TITLE
start the game over the server When we create a room, it opens as 127.0.0.1 instead of the server.

### ISSUE THREAD

**Issue by IGNRexI** [Ochii/cso2-master-services#37] opened 2020-03-31 13:59 UTC
When we create a room, it opens as 127.0.0.1 instead of the server.
in short 
I think the opened rooms should be hosted on the server so that the players do not have connection problems
Currently, when we start the room game, the server starts from our own computer.

**Comment by lateleite** [comment] 2020-03-31 15:24
Duplicate of https://github.com/L-Leite/cso2-master-server/issues/47

**Closed as completed by lateleite** 2020-03-31 15:24 UTC
